### ISSUE TITLE
Script fails to run

### ISSUE THREAD

**Issue by gandalf3** [swick/irssi-passwd#3]
When I do `/script run passwd.pl`, I get

    Excessively long <> operator at /usr/share/irssi/scripts/passwd.pl line 21.

Perl v5.28.2, irssi 1.2.0

**Comment by gandalf3** [comment]
User error; please disregard

**Comment by v8ive** [comment]
> User error; please disregard

Could you explain how this was solved? Running across a similar issue on another script....

**Comment by kitt-cat** [comment]
@v8ive I'm sorry, I don't remember.. Maybe if you can give me some details about your script I might be able to figure out how to reproduce the problem again?

----
I have a vague recollection I had a config file in the wrong place, that may or may not have been this problem.

**Comment by v8ive** [comment]
It's all good, figured it out, I was using an outdated script referencing a source that wasn't available anymore. I appreciate the response though!
