### ISSUE TITLE
/passwd gives error "Not connected to server"

### ISSUE THREAD

**Issue by gandalf3** [swick/irssi-passwd#4]
Running

    /passwd some_pw_id /msg NickServ <password>

Complains `Not connected to server`, even when I am. However, when the command is `/echo`, it works as expected.

**Comment by swick** [comment]
Hi, I don't have any interest in maintaining this project. If you want I can add a note to the README which forwards users to your repository.

**Comment by gandalf3** [comment]
@swick Fair enough, that sounds good to me. Thanks for writing it :)

**Comment by swick** [comment]
No problem. Updated the README. Have fun!

**Comment by gandalf3** [comment]
Thanks! By the way, would you mind licensing it? (GPL would be fine)
 I'd like to declare a license for my fork, but I don't think I can without upstream having a license.

**Comment by swick** [comment]
Oh wow, didn't notice a license was missing. That was a long time ago. Thanks for pointing that out.

a6875a116a0b1cc3ee0d77c12fc67bf55a153ce8
